# Generated by Django 5.1.4 on 2024-12-23 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[("f", "feedback analysis"), ("c", "chat request")],
                        max_length=1,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="GeminiModel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
