# Generated by Django 5.1.4 on 2024-12-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("course_name", models.CharField(max_length=25)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("e", "english"),
                            ("s", "science"),
                            ("m", "math"),
                            ("c", "career"),
                            ("s", "special"),
                            ("g", "general"),
                        ],
                        max_length=1,
                    ),
                ),
                ("reason", models.CharField(max_length=250)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ExtracurricularModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("extracurricular_name", models.CharField(max_length=30)),
                ("reason", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="extracurricular/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPAModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("number", models.FloatField()),
            ],
        ),
    ]
