# Generated by Django 5.1.4 on 2024-12-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_rename_date_extracurricularmodel_ext_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extracurricularmodel",
            old_name="ext_date",
            new_name="date",
        ),
    ]
