# Generated by Django 5.1.4 on 2024-12-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                (
                    "praise_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a", "academic"),
                            ("e", "extracurricular"),
                            ("r", "relationship"),
                            ("c", "characteristic"),
                            ("g", "general"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "length_type",
                    models.CharField(
                        blank=True,
                        choices=[("s", "short"), ("l", "long")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
